/*
 * generated by Xtext
 */
package org.eclipse.sirius.expression.text.ui.contentassist

import org.eclipse.sirius.expression.text.ui.contentassist.AbstractExpressionTextProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ExpressionTextProposalProvider extends AbstractExpressionTextProposalProvider {
}
