/*
 * generated by Xtext
 */
package org.eclipse.emf.eef.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ModelingBotUiModule extends org.eclipse.emf.eef.ui.AbstractModelingBotUiModule {
	public ModelingBotUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
