/*
 * generated by Xtext
 */
package org.eclipse.sirius.expression.text;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ExpressionTextStandaloneSetup extends ExpressionTextStandaloneSetupGenerated{

	public static void doSetup() {
		new ExpressionTextStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

