package org.eclipse.eef.documentation.validator.api;

public enum ValidationStatusKind {
	UNDOCUMENTED_ECLASSIFIER,
	UNDOCUMENTED_ESTRUCTURAL_FEATURE,
	ECLASSIFIER_NOT_FOUND,
	ESTRUCUTURAL_FEATURE_NOT_FOUND,
	INVALID_EATTRIBUTE_TYPE,
	INVALID_EREFERENCE_TYPE,
	INVALID_LOWER_BOUND,
	INVALID_UPPER_BOUND,
	INVALID_EREFERENCE_CONTAINMENT
}
