/*
 * generated by Xtext
 */
package org.eclipse.sirius.expression.text.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.sirius.expression.text.ui.internal.ExpressionTextActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ExpressionTextExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ExpressionTextActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ExpressionTextActivator.getInstance().getInjector(ExpressionTextActivator.ORG_ECLIPSE_SIRIUS_EXPRESSION_TEXT_EXPRESSIONTEXT);
	}
	
}
