package org.eclipse.emf.eef.tests.nonreg;

import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;

import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotAddAdvTableCompoOnAbstractRef;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotAddTableCompo;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotCancelAddTableCompo;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotCancelSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotCancelSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotCancelSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotRedoAddTableCompo;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotRedoSetAttributeRadio;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotRedoSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotRedoSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotRedoSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotRemoveTableCompo;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotSetAttributeRadio;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotUndoAddTableCompo;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotUndoSetAttributeRadio;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotUndoSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotUndoSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotUndoSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotUnsetAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotUnsetEOFCV;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotUnsetFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotUnsetRefTable;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotUnsetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotUnsetReferenceEOFCV;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotUnsetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.batch.detailsview.BatchMBotUnsetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotAddAdvTableCompoOnAbstractRef;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotAddTableCompo;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotCancelAddTableCompo;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotCancelSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotCancelSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotCancelSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotRedoAddTableCompo;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotRedoSetAttributeRadio;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotRedoSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotRedoSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotRedoSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotRemoveTableCompo;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotSetAttributeRadio;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotUndoAddTableCompo;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotUndoSetAttributeRadio;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotUndoSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotUndoSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotUndoSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotUnsetAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotUnsetEOFCV;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotUnsetFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotUnsetRefTable;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotUnsetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotUnsetReferenceEOFCV;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotUnsetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.composed.detailsview.ComposedMBotUnsetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotAddAdvTableCompoOnAbstractRef;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotAddTableCompo;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotCancelAddTableCompo;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotCancelSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotCancelSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotCancelSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotRedoAddTableCompo;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotRedoSetAttributeRadio;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotRedoSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotRedoSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotRedoSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotRemoveTableCompo;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotSetAttributeRadio;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotUndoAddTableCompo;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotUndoSetAttributeRadio;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotUndoSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotUndoSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotUndoSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotUnsetAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotUnsetEOFCV;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotUnsetFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotUnsetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.detailsview.MBotUnsetReferenceEOFCV;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotAddTableComposition;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotCancelAddTableComposition;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotCancelSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotCancelSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotCancelSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotEditSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotEditSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotMoveTableComposition;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotRedoAddTableComposition;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotRedoSetAttributeRadio;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotRedoSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotRedoSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotRedoSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotRemoveTableComposition;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotSetAttributeRadio;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotUndoAddTableComposition;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotUndoSetAttributeRadio;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotUndoSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotUndoSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotUndoSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotUnsetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotUnsetReferenceEOFCV;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotUnsetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotUnsetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.propertiesView.PViewMBotUnsetReferencesTable;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotCancelSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotCancelSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotCancelSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotEditSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotEditSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotEditSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotRedoSetAttributeRadio;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotRedoSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotRedoSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotRedoSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotSetAttributeRadio;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotUndoSetAttributeRadio;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotUndoSetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotUndoSetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotUndoSetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotUnsetAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotUnsetEOFCV;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotUnsetFlatReferencesTable;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotUnsetReferenceAEOFCV;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotUnsetReferenceFlatRefTable;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotUnsetReferenceRefTable;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotUnsetReferencesTable;
import org.eclipse.emf.eef.tests.nonreg.wizard.WizardMBotUnsetTextArea;

public class AllTests extends TestCase {

	public static Test suite() {
		TestSuite suite = new TestSuite(AllTests.class.getName());
		//$JUnit-BEGIN$
//		suite.addTestSuite(BatchMBotAddAdvTableCompoOnAbstractRef.class);
//		suite.addTestSuite(BatchMBotAddTableCompo.class);
//		suite.addTestSuite(BatchMBotCancelAddTableCompo.class);
//		suite.addTestSuite(BatchMBotCancelSetReferenceAEOFCV.class);
//		suite.addTestSuite(BatchMBotCancelSetReferenceFlatRefTable.class);
//		suite.addTestSuite(BatchMBotCancelSetReferenceRefTable.class);
//		suite.addTestSuite(BatchMBotRedoAddTableCompo.class);
//		suite.addTestSuite(BatchMBotRedoSetAttributeRadio.class);
//		suite.addTestSuite(BatchMBotRedoSetReferenceAEOFCV.class);
//		suite.addTestSuite(BatchMBotRedoSetReferenceFlatRefTable.class);
//		suite.addTestSuite(BatchMBotRedoSetReferenceRefTable.class);
//		suite.addTestSuite(BatchMBotRemoveTableCompo.class);
//		suite.addTestSuite(BatchMBotSetAttributeRadio.class);
//		suite.addTestSuite(BatchMBotSetReferenceAEOFCV.class);
//		suite.addTestSuite(BatchMBotSetReferenceFlatRefTable.class);
//		suite.addTestSuite(BatchMBotSetReferenceRefTable.class);
//		suite.addTestSuite(BatchMBotUndoAddTableCompo.class);
//		suite.addTestSuite(BatchMBotUndoSetAttributeRadio.class);
//		suite.addTestSuite(BatchMBotUndoSetReferenceAEOFCV.class);
//		suite.addTestSuite(BatchMBotUndoSetReferenceFlatRefTable.class);
//		suite.addTestSuite(BatchMBotUndoSetReferenceRefTable.class);
//		suite.addTestSuite(BatchMBotUnsetAEOFCV.class);
//		suite.addTestSuite(BatchMBotUnsetEOFCV.class);
//		suite.addTestSuite(BatchMBotUnsetFlatRefTable.class);
//		suite.addTestSuite(BatchMBotUnsetReferenceAEOFCV.class);
//		suite.addTestSuite(BatchMBotUnsetReferenceEOFCV.class);
//		suite.addTestSuite(BatchMBotUnsetReferenceFlatRefTable.class);
//		suite.addTestSuite(BatchMBotUnsetReferenceRefTable.class);
//		suite.addTestSuite(BatchMBotUnsetRefTable.class);
//		
//		// Details
//		suite.addTestSuite(MBotAddAdvTableCompoOnAbstractRef.class);
//		suite.addTestSuite(MBotAddTableCompo.class);
//		suite.addTestSuite(MBotCancelAddTableCompo.class);
//		suite.addTestSuite(MBotCancelSetReferenceAEOFCV.class);
//		suite.addTestSuite(MBotCancelSetReferenceFlatRefTable.class);
//		suite.addTestSuite(MBotCancelSetReferenceRefTable.class);
//		suite.addTestSuite(MBotRedoAddTableCompo.class);
//		suite.addTestSuite(MBotRedoSetAttributeRadio.class);
//		suite.addTestSuite(MBotRedoSetReferenceAEOFCV.class);
//		suite.addTestSuite(MBotRedoSetReferenceFlatRefTable.class);
//		suite.addTestSuite(MBotRedoSetReferenceRefTable.class);
//		suite.addTestSuite(MBotRemoveTableCompo.class);
//		suite.addTestSuite(MBotSetAttributeRadio.class);
//		suite.addTestSuite(MBotSetReferenceAEOFCV.class);
//		suite.addTestSuite(MBotSetReferenceFlatRefTable.class);
//		suite.addTestSuite(MBotSetReferenceRefTable.class);
//		suite.addTestSuite(MBotUndoAddTableCompo.class);
//		suite.addTestSuite(MBotUndoSetAttributeRadio.class);
//		suite.addTestSuite(MBotUndoSetReferenceAEOFCV.class);
//		suite.addTestSuite(MBotUndoSetReferenceFlatRefTable.class);
//		suite.addTestSuite(MBotUndoSetReferenceRefTable.class);
//		suite.addTestSuite(MBotUnsetAEOFCV.class);
//		suite.addTestSuite(MBotUnsetEOFCV.class);
//		suite.addTestSuite(MBotUnsetFlatRefTable.class);
//		suite.addTestSuite(MBotUnsetReferenceAEOFCV.class);
//		suite.addTestSuite(MBotUnsetReferenceEOFCV.class);
////		suite.addTestSuite(MBotUnsetReferenceFlatRefTable.class);
////		suite.addTestSuite(MBotUnsetReferenceRefTable.class);
////		suite.addTestSuite(MBotUnsetRefTable.class);
//		
//		
//		// Properties Views
//		suite.addTestSuite(PViewMBotAddTableComposition.class);
//		suite.addTestSuite(PViewMBotCancelAddTableComposition.class);
//		suite.addTestSuite(PViewMBotCancelSetReferenceAEOFCV.class);
//		suite.addTestSuite(PViewMBotCancelSetReferenceFlatRefTable.class);
//		suite.addTestSuite(PViewMBotCancelSetReferenceRefTable.class);
////		suite.addTestSuite(PViewMBotEditSetReferenceAEOFCV.class);
////		suite.addTestSuite(PViewMBotEditSetReferenceCombo.class);
//		suite.addTestSuite(PViewMBotEditSetReferenceFlatRefTable.class);
//		suite.addTestSuite(PViewMBotEditSetReferenceRefTable.class);
//		suite.addTestSuite(PViewMBotMoveTableComposition.class);
//		suite.addTestSuite(PViewMBotRedoAddTableComposition.class);
//		suite.addTestSuite(PViewMBotRedoSetAttributeRadio.class);
//		suite.addTestSuite(PViewMBotRedoSetReferenceAEOFCV.class);
////		suite.addTestSuite(PViewMBotRedoSetReferenceCombo.class);
//		suite.addTestSuite(PViewMBotRedoSetReferenceFlatRefTable.class);
//		suite.addTestSuite(PViewMBotRedoSetReferenceRefTable.class);
//		suite.addTestSuite(PViewMBotRemoveTableComposition.class);
//		suite.addTestSuite(PViewMBotSetAttributeRadio.class);
//		suite.addTestSuite(PViewMBotSetReferenceAEOFCV.class);
////		suite.addTestSuite(PViewMBotSetReferenceCombo.class);
//		suite.addTestSuite(PViewMBotSetReferenceFlatRefTable.class);
////		suite.addTestSuite(PViewMBotSetReferenceRefTable.class);
//		suite.addTestSuite(PViewMBotUndoAddTableComposition.class);
//		suite.addTestSuite(PViewMBotUndoSetAttributeRadio.class);
//		suite.addTestSuite(PViewMBotUndoSetReferenceAEOFCV.class);
////		suite.addTestSuite(PViewMBotUndoSetReferenceCombo.class);
//		suite.addTestSuite(PViewMBotUndoSetReferenceFlatRefTable.class);
//		suite.addTestSuite(PViewMBotUndoSetReferenceRefTable.class);
////		suite.addTestSuite(PViewMBotUnsetAEOFCV.class);
////		suite.addTestSuite(PViewMBotUnsetCombo.class);
////		suite.addTestSuite(PViewMBotUnsetEOFCV.class);
////		suite.addTestSuite(PViewMBotUnsetFlatReferencesTable.class);
//		suite.addTestSuite(PViewMBotUnsetReferenceAEOFCV.class);
////		suite.addTestSuite(PViewMBotUnsetReferenceCombo.class);
//		suite.addTestSuite(PViewMBotUnsetReferenceEOFCV.class);
//		suite.addTestSuite(PViewMBotUnsetReferenceFlatRefTable.class);
//		suite.addTestSuite(PViewMBotUnsetReferenceRefTable.class);
//		suite.addTestSuite(PViewMBotUnsetReferencesTable.class);
//		
//		// Wizards
//		
//// It should'nt have never passed !
////		suite.addTestSuite(WizardMBotAddTableComposition.class);
////		suite.addTestSuite(WizardMBotCancelAddTableComposition.class);
//		suite.addTestSuite(WizardMBotCancelSetReferenceAEOFCV.class);
//		suite.addTestSuite(WizardMBotCancelSetReferenceFlatRefTable.class);
//		suite.addTestSuite(WizardMBotCancelSetReferenceRefTable.class);
//		suite.addTestSuite(WizardMBotEditSetReferenceAEOFCV.class);
//		suite.addTestSuite(WizardMBotEditSetReferenceFlatRefTable.class);
//		suite.addTestSuite(WizardMBotEditSetReferenceRefTable.class);
////		suite.addTestSuite(WizardMBotRedoAddTableComposition.class);
//		suite.addTestSuite(WizardMBotRedoSetAttributeRadio.class);
//		suite.addTestSuite(WizardMBotRedoSetReferenceAEOFCV.class);
//		suite.addTestSuite(WizardMBotRedoSetReferenceFlatRefTable.class);
//		suite.addTestSuite(WizardMBotRedoSetReferenceRefTable.class);
////		suite.addTestSuite(WizardMBotRemoveTableComposition.class);
//		suite.addTestSuite(WizardMBotSetAttributeRadio.class);
//		suite.addTestSuite(WizardMBotSetReferenceAEOFCV.class);
//		suite.addTestSuite(WizardMBotSetReferenceFlatRefTable.class);
//		suite.addTestSuite(WizardMBotSetReferenceRefTable.class);
////		suite.addTestSuite(WizardMBotUndoAddTableComposition.class);
//		suite.addTestSuite(WizardMBotUndoSetAttributeRadio.class);
//		suite.addTestSuite(WizardMBotUndoSetReferenceAEOFCV.class);
//		suite.addTestSuite(WizardMBotUndoSetReferenceFlatRefTable.class);
//		suite.addTestSuite(WizardMBotUndoSetReferenceRefTable.class);
//		suite.addTestSuite(WizardMBotUnsetAEOFCV.class);
//		suite.addTestSuite(WizardMBotUnsetEOFCV.class);
//		suite.addTestSuite(WizardMBotUnsetFlatReferencesTable.class);
//		suite.addTestSuite(WizardMBotUnsetReferenceAEOFCV.class);
//		suite.addTestSuite(WizardMBotUnsetReferenceFlatRefTable.class);
//		suite.addTestSuite(WizardMBotUnsetReferenceRefTable.class);
//		suite.addTestSuite(WizardMBotUnsetReferencesTable.class);
//		suite.addTestSuite(WizardMBotUnsetTextArea.class);
		
		// Composed
//		suite.addTestSuite(ComposedMBotAddAdvTableCompoOnAbstractRef.class);
//		suite.addTestSuite(ComposedMBotAddTableCompo.class);
		suite.addTestSuite(ComposedMBotCancelAddTableCompo.class);
		suite.addTestSuite(ComposedMBotCancelSetReferenceAEOFCV.class);
		suite.addTestSuite(ComposedMBotCancelSetReferenceFlatRefTable.class);
		suite.addTestSuite(ComposedMBotCancelSetReferenceRefTable.class);
//		suite.addTestSuite(ComposedMBotRedoAddTableCompo.class);
//		suite.addTestSuite(ComposedMBotRedoSetAttributeRadio.class);
//		suite.addTestSuite(ComposedMBotRedoSetReferenceAEOFCV.class);
		suite.addTestSuite(ComposedMBotRedoSetReferenceFlatRefTable.class);
		suite.addTestSuite(ComposedMBotRedoSetReferenceRefTable.class);
		suite.addTestSuite(ComposedMBotRemoveTableCompo.class);
//		suite.addTestSuite(ComposedMBotSetAttributeRadio.class);
		suite.addTestSuite(ComposedMBotSetReferenceAEOFCV.class);
		suite.addTestSuite(ComposedMBotSetReferenceFlatRefTable.class);
//		suite.addTestSuite(ComposedMBotSetReferenceRefTable.class);
		suite.addTestSuite(ComposedMBotUndoAddTableCompo.class);
//		suite.addTestSuite(ComposedMBotUndoSetAttributeRadio.class);
		suite.addTestSuite(ComposedMBotUndoSetReferenceAEOFCV.class);
		suite.addTestSuite(ComposedMBotUndoSetReferenceFlatRefTable.class);
		suite.addTestSuite(ComposedMBotUndoSetReferenceRefTable.class);
		suite.addTestSuite(ComposedMBotUnsetAEOFCV.class);
		suite.addTestSuite(ComposedMBotUnsetEOFCV.class);
		suite.addTestSuite(ComposedMBotUnsetFlatRefTable.class);
		suite.addTestSuite(ComposedMBotUnsetReferenceAEOFCV.class);
		suite.addTestSuite(ComposedMBotUnsetReferenceEOFCV.class);
		suite.addTestSuite(ComposedMBotUnsetReferenceFlatRefTable.class);
		suite.addTestSuite(ComposedMBotUnsetReferenceRefTable.class);
		suite.addTestSuite(ComposedMBotUnsetRefTable.class);
		//$JUnit-END$
		return suite;
	}

}
