<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="worldcupforecast"
    nsURI="http://wwww.obeo.fr/dsl/worldcupforecast/1.0.0" nsPrefix="worldcupforecast">
  <eClassifiers xsi:type="ecore:EClass" name="WorldCupForecast">
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="#//WorldCupGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="players" upperBound="-1"
        eType="#//Player" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matchDays" upperBound="-1"
        eType="#//MatchDay" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validatePlayers" upperBound="-1"
        eType="#//ValidatePlayer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Forecast" eSuperTypes="#//Score">
    <eStructuralFeatures xsi:type="ecore:EReference" name="match" lowerBound="1" eType="#//Match"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="winner" eType="#//Team"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Match" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hours" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minutes" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coefficient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="score" eType="#//FinalScore"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="team1" lowerBound="1" eType="#//Team"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="team2" lowerBound="1" eType="#//Team"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Score" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scoreTeam1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scoreTeam2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Team">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="points" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goalsFor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goalsAgainst" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goalDifference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="played" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorldCupGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="teams" upperBound="4" eType="#//Team"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player">
    <eOperations name="goodForecastNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="perfectForecastsNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forecastDays" upperBound="-1"
        eType="#//ForecastDay" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidatePlayer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" lowerBound="1"
        eType="#//Player"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forecastDays" upperBound="-1"
        eType="#//ForecastDay" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinalScore" eSuperTypes="#//Score">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="penaltyScoreTeam1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="penaltyScoreTeam2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="winner" eType="#//Team"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatchDay" eSuperTypes="#//Day">
    <eStructuralFeatures xsi:type="ecore:EReference" name="matches" upperBound="-1"
        eType="#//Match" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForecastDay" eSuperTypes="#//Day">
    <eStructuralFeatures xsi:type="ecore:EReference" name="forecasts" upperBound="-1"
        eType="#//Forecast" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Day" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupStageMatch" eSuperTypes="#//Match">
    <eStructuralFeatures xsi:type="ecore:EReference" name="manualTeam1" lowerBound="1"
        eType="#//Team"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manualTeam2" lowerBound="1"
        eType="#//Team"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OtherKnockoutStageMatch" eSuperTypes="#//KnockoutStageMatch">
    <eStructuralFeatures xsi:type="ecore:EReference" name="team1WinnerOfMatch" lowerBound="1"
        eType="#//Match"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="team2WinnerOfMatch" lowerBound="1"
        eType="#//Match"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//MatchType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThirdPlaceMatch" eSuperTypes="#//KnockoutStageMatch">
    <eStructuralFeatures xsi:type="ecore:EReference" name="team1LooserOfMatch" lowerBound="1"
        eType="#//Match"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="team2LooserOfMatch" lowerBound="1"
        eType="#//Match"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoundOfSixteenMatch" eSuperTypes="#//KnockoutStageMatch">
    <eStructuralFeatures xsi:type="ecore:EReference" name="team1WinnerOfGroup" lowerBound="1"
        eType="#//WorldCupGroup"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="team2RunnerUpOfGroup" lowerBound="1"
        eType="#//WorldCupGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KnockoutStageMatch" abstract="true"
      eSuperTypes="#//Match">
    <eStructuralFeatures xsi:type="ecore:EReference" name="calculatedTeam1" lowerBound="1"
        eType="#//Team" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calculatedTeam2" lowerBound="1"
        eType="#//Team" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MatchType">
    <eLiterals name="quarterFinal" value="2" literal="Quarter-final"/>
    <eLiterals name="semiFinal" value="3" literal="Semi-final"/>
    <eLiterals name="final" value="4" literal="Final"/>
  </eClassifiers>
</ecore:EPackage>
