/*
 * generated by Xtext
 */
package org.eclipse.sirius.expression.text.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExpressionTextUiModule extends org.eclipse.sirius.expression.text.ui.AbstractExpressionTextUiModule {
	public ExpressionTextUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
