/*
 * generated by Xtext
 */
package org.eclipse.sirius.expression.dsl;

import org.eclipse.sirius.expression.dsl.scoping.ExpressionDSLStatedContainerManager;
import org.eclipse.xtext.resource.IContainer.Manager;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExpressionDSLRuntimeModule extends org.eclipse.sirius.expression.dsl.AbstractExpressionDSLRuntimeModule {
//	public Class<? extends org.eclipse.xtext.scoping.IGlobalScopeProvider> bindIGlobalScopeProvider() {
//		return ExpressionDSLGlobalScopeProvider.class;
//	}
	
	@Override
	public Class<? extends Manager> bindIContainer$Manager() {
		return ExpressionDSLStatedContainerManager.class;
	}
}
