/*
* generated by Xtext
*/
package org.eclipse.emf.eef.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ModelingBotProposalProvider extends org.eclipse.emf.eef.ui.contentassist.AbstractModelingBotProposalProvider {

}
