/**
 * generated by Xtext
 */
package org.eclipse.sirius.expression.text.validation;

import org.eclipse.sirius.expression.text.validation.AbstractExpressionTextValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ExpressionTextValidator extends AbstractExpressionTextValidator {
}
