/*
* generated by Xtext
*/
package org.eclipse.emf.eef.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.eclipse.emf.eef.services.ModelingBotGrammarAccess;

public class ModelingBotParser extends AbstractContentAssistParser {
	
	@Inject
	private ModelingBotGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.eclipse.emf.eef.ui.contentassist.antlr.internal.InternalModelingBotParser createParser() {
		org.eclipse.emf.eef.ui.contentassist.antlr.internal.InternalModelingBotParser result = new org.eclipse.emf.eef.ui.contentassist.antlr.internal.InternalModelingBotParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getProcessingsAccess().getAlternatives(), "rule__Processings__Alternatives");
					put(grammarAccess.getSubProcessingsAccess().getAlternatives(), "rule__SubProcessings__Alternatives");
					put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
					put(grammarAccess.getEclipseActionAccess().getAlternatives(), "rule__EclipseAction__Alternatives");
					put(grammarAccess.getReferenceableObjectAccess().getAlternatives(), "rule__ReferenceableObject__Alternatives");
					put(grammarAccess.getEEFActionAccess().getAlternatives(), "rule__EEFAction__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getScenarioAccess().getGroup(), "rule__Scenario__Group__0");
					put(grammarAccess.getPropertiesViewAccess().getGroup(), "rule__PropertiesView__Group__0");
					put(grammarAccess.getWizardAccess().getGroup(), "rule__Wizard__Group__0");
					put(grammarAccess.getDetailsAccess().getGroup(), "rule__Details__Group__0");
					put(grammarAccess.getCreateProjectAccess().getGroup(), "rule__CreateProject__Group__0");
					put(grammarAccess.getRemoveProjectAccess().getGroup(), "rule__RemoveProject__Group__0");
					put(grammarAccess.getCreateModelAccess().getGroup(), "rule__CreateModel__Group__0");
					put(grammarAccess.getSaveAccess().getGroup(), "rule__Save__Group__0");
					put(grammarAccess.getCheckAccess().getGroup(), "rule__Check__Group__0");
					put(grammarAccess.getAddAccess().getGroup(), "rule__Add__Group__0");
					put(grammarAccess.getSetAttributeAccess().getGroup(), "rule__SetAttribute__Group__0");
					put(grammarAccess.getSetAttributeAccess().getGroup_4(), "rule__SetAttribute__Group_4__0");
					put(grammarAccess.getSetAttributeAccess().getGroup_7(), "rule__SetAttribute__Group_7__0");
					put(grammarAccess.getScenarioAccess().getNameAssignment_1(), "rule__Scenario__NameAssignment_1");
					put(grammarAccess.getScenarioAccess().getProcessingsAssignment_3(), "rule__Scenario__ProcessingsAssignment_3");
					put(grammarAccess.getPropertiesViewAccess().getNameAssignment_1(), "rule__PropertiesView__NameAssignment_1");
					put(grammarAccess.getPropertiesViewAccess().getProcessingsAssignment_3(), "rule__PropertiesView__ProcessingsAssignment_3");
					put(grammarAccess.getWizardAccess().getNameAssignment_1(), "rule__Wizard__NameAssignment_1");
					put(grammarAccess.getWizardAccess().getProcessingsAssignment_3(), "rule__Wizard__ProcessingsAssignment_3");
					put(grammarAccess.getDetailsAccess().getNameAssignment_1(), "rule__Details__NameAssignment_1");
					put(grammarAccess.getDetailsAccess().getProcessingsAssignment_3(), "rule__Details__ProcessingsAssignment_3");
					put(grammarAccess.getCreateProjectAccess().getProjectNameAssignment_1(), "rule__CreateProject__ProjectNameAssignment_1");
					put(grammarAccess.getRemoveProjectAccess().getProjectNameAssignment_1(), "rule__RemoveProject__ProjectNameAssignment_1");
					put(grammarAccess.getCreateModelAccess().getReferenceNameAssignment_1(), "rule__CreateModel__ReferenceNameAssignment_1");
					put(grammarAccess.getCreateModelAccess().getRootURIAssignment_3(), "rule__CreateModel__RootURIAssignment_3");
					put(grammarAccess.getCreateModelAccess().getModelNameAssignment_5(), "rule__CreateModel__ModelNameAssignment_5");
					put(grammarAccess.getCreateModelAccess().getPathAssignment_7(), "rule__CreateModel__PathAssignment_7");
					put(grammarAccess.getAddAccess().getReferenceNameAssignment_1(), "rule__Add__ReferenceNameAssignment_1");
					put(grammarAccess.getAddAccess().getTypeURIAssignment_3(), "rule__Add__TypeURIAssignment_3");
					put(grammarAccess.getAddAccess().getReferenceableObjectAssignment_5(), "rule__Add__ReferenceableObjectAssignment_5");
					put(grammarAccess.getAddAccess().getEContainingFeatureURIAssignment_7(), "rule__Add__EContainingFeatureURIAssignment_7");
					put(grammarAccess.getSetAttributeAccess().getReferenceableObjectAssignment_1(), "rule__SetAttribute__ReferenceableObjectAssignment_1");
					put(grammarAccess.getSetAttributeAccess().getValuesAssignment_3(), "rule__SetAttribute__ValuesAssignment_3");
					put(grammarAccess.getSetAttributeAccess().getValuesAssignment_4_1(), "rule__SetAttribute__ValuesAssignment_4_1");
					put(grammarAccess.getSetAttributeAccess().getEContainingFeatureURIAssignment_6(), "rule__SetAttribute__EContainingFeatureURIAssignment_6");
					put(grammarAccess.getSetAttributeAccess().getPropertiesEditionElementURIAssignment_7_1(), "rule__SetAttribute__PropertiesEditionElementURIAssignment_7_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.eclipse.emf.eef.ui.contentassist.antlr.internal.InternalModelingBotParser typedParser = (org.eclipse.emf.eef.ui.contentassist.antlr.internal.InternalModelingBotParser) parser;
			typedParser.entryRuleScenario();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ModelingBotGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ModelingBotGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
