/*
 * generated by Xtext
 */
package org.eclipse.sirius.expression.text.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.sirius.expression.text.services.ExpressionTextGrammarAccess;

public class ExpressionTextParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ExpressionTextGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	
	@Override
	protected org.eclipse.sirius.expression.text.parser.antlr.internal.InternalExpressionTextParser createParser(XtextTokenStream stream) {
		return new org.eclipse.sirius.expression.text.parser.antlr.internal.InternalExpressionTextParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "SiriusExpressionPackage";
	}
	
	public ExpressionTextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ExpressionTextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
