/*
 * generated by Xtext
 */
package org.eclipse.sirius.expression.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.sirius.expression.dsl.services.ExpressionDSLGrammarAccess;

public class ExpressionDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ExpressionDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	
	@Override
	protected org.eclipse.sirius.expression.dsl.parser.antlr.internal.InternalExpressionDSLParser createParser(XtextTokenStream stream) {
		return new org.eclipse.sirius.expression.dsl.parser.antlr.internal.InternalExpressionDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "SiriusExpressionPackage";
	}
	
	public ExpressionDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ExpressionDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
