/*
 * generated by Xtext
 */
package org.eclipse.sirius.expression.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.sirius.expression.dsl.ui.internal.ExpressionDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ExpressionDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ExpressionDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ExpressionDSLActivator.getInstance().getInjector(ExpressionDSLActivator.ORG_ECLIPSE_SIRIUS_EXPRESSION_DSL_EXPRESSIONDSL);
	}
	
}
