/**
 * Copyright (c) 2015 Obeo.
 * All rights reserved. This program and the accompanying materials 
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.htm
 * Contributors: Obeo - initial API and implementation
 */
package org.eclipse.eef.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.eef.util.EefAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class EefItemProviderAdapterFactory extends EefAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EefItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFViewDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFViewDescriptionItemProvider eefViewDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFViewDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFViewDescriptionAdapter() {
		if (eefViewDescriptionItemProvider == null) {
			eefViewDescriptionItemProvider = new EEFViewDescriptionItemProvider(this);
		}

		return eefViewDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFPageDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFPageDescriptionItemProvider eefPageDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFPageDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFPageDescriptionAdapter() {
		if (eefPageDescriptionItemProvider == null) {
			eefPageDescriptionItemProvider = new EEFPageDescriptionItemProvider(this);
		}

		return eefPageDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFGroupDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFGroupDescriptionItemProvider eefGroupDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFGroupDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFGroupDescriptionAdapter() {
		if (eefGroupDescriptionItemProvider == null) {
			eefGroupDescriptionItemProvider = new EEFGroupDescriptionItemProvider(this);
		}

		return eefGroupDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFContainerDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFContainerDescriptionItemProvider eefContainerDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFContainerDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFContainerDescriptionAdapter() {
		if (eefContainerDescriptionItemProvider == null) {
			eefContainerDescriptionItemProvider = new EEFContainerDescriptionItemProvider(this);
		}

		return eefContainerDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFJavaExtensionDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFJavaExtensionDescriptionItemProvider eefJavaExtensionDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFJavaExtensionDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFJavaExtensionDescriptionAdapter() {
		if (eefJavaExtensionDescriptionItemProvider == null) {
			eefJavaExtensionDescriptionItemProvider = new EEFJavaExtensionDescriptionItemProvider(this);
		}

		return eefJavaExtensionDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFInterpretedTableStructureDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFInterpretedTableStructureDescriptionItemProvider eefInterpretedTableStructureDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFInterpretedTableStructureDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFInterpretedTableStructureDescriptionAdapter() {
		if (eefInterpretedTableStructureDescriptionItemProvider == null) {
			eefInterpretedTableStructureDescriptionItemProvider = new EEFInterpretedTableStructureDescriptionItemProvider(this);
		}

		return eefInterpretedTableStructureDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFAdapterFactoryTreeStructureDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFAdapterFactoryTreeStructureDescriptionItemProvider eefAdapterFactoryTreeStructureDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFAdapterFactoryTreeStructureDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFAdapterFactoryTreeStructureDescriptionAdapter() {
		if (eefAdapterFactoryTreeStructureDescriptionItemProvider == null) {
			eefAdapterFactoryTreeStructureDescriptionItemProvider = new EEFAdapterFactoryTreeStructureDescriptionItemProvider(this);
		}

		return eefAdapterFactoryTreeStructureDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFInterpretedTreeStructureDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFInterpretedTreeStructureDescriptionItemProvider eefInterpretedTreeStructureDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFInterpretedTreeStructureDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFInterpretedTreeStructureDescriptionAdapter() {
		if (eefInterpretedTreeStructureDescriptionItemProvider == null) {
			eefInterpretedTreeStructureDescriptionItemProvider = new EEFInterpretedTreeStructureDescriptionItemProvider(this);
		}

		return eefInterpretedTreeStructureDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFTextDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFTextDescriptionItemProvider eefTextDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFTextDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFTextDescriptionAdapter() {
		if (eefTextDescriptionItemProvider == null) {
			eefTextDescriptionItemProvider = new EEFTextDescriptionItemProvider(this);
		}

		return eefTextDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFCheckboxDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFCheckboxDescriptionItemProvider eefCheckboxDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFCheckboxDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFCheckboxDescriptionAdapter() {
		if (eefCheckboxDescriptionItemProvider == null) {
			eefCheckboxDescriptionItemProvider = new EEFCheckboxDescriptionItemProvider(this);
		}

		return eefCheckboxDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFSelectDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFSelectDescriptionItemProvider eefSelectDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFSelectDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFSelectDescriptionAdapter() {
		if (eefSelectDescriptionItemProvider == null) {
			eefSelectDescriptionItemProvider = new EEFSelectDescriptionItemProvider(this);
		}

		return eefSelectDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFLabelDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFLabelDescriptionItemProvider eefLabelDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFLabelDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFLabelDescriptionAdapter() {
		if (eefLabelDescriptionItemProvider == null) {
			eefLabelDescriptionItemProvider = new EEFLabelDescriptionItemProvider(this);
		}

		return eefLabelDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFRadioDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFRadioDescriptionItemProvider eefRadioDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFRadioDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFRadioDescriptionAdapter() {
		if (eefRadioDescriptionItemProvider == null) {
			eefRadioDescriptionItemProvider = new EEFRadioDescriptionItemProvider(this);
		}

		return eefRadioDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFTreeDialogSelectDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFTreeDialogSelectDescriptionItemProvider eefTreeDialogSelectDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFTreeDialogSelectDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFTreeDialogSelectDescriptionAdapter() {
		if (eefTreeDialogSelectDescriptionItemProvider == null) {
			eefTreeDialogSelectDescriptionItemProvider = new EEFTreeDialogSelectDescriptionItemProvider(this);
		}

		return eefTreeDialogSelectDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFLinkDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFLinkDescriptionItemProvider eefLinkDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFLinkDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFLinkDescriptionAdapter() {
		if (eefLinkDescriptionItemProvider == null) {
			eefLinkDescriptionItemProvider = new EEFLinkDescriptionItemProvider(this);
		}

		return eefLinkDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFImageDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFImageDescriptionItemProvider eefImageDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFImageDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFImageDescriptionAdapter() {
		if (eefImageDescriptionItemProvider == null) {
			eefImageDescriptionItemProvider = new EEFImageDescriptionItemProvider(this);
		}

		return eefImageDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFTreeDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFTreeDescriptionItemProvider eefTreeDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFTreeDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFTreeDescriptionAdapter() {
		if (eefTreeDescriptionItemProvider == null) {
			eefTreeDescriptionItemProvider = new EEFTreeDescriptionItemProvider(this);
		}

		return eefTreeDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFImagePickerDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFImagePickerDescriptionItemProvider eefImagePickerDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFImagePickerDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFImagePickerDescriptionAdapter() {
		if (eefImagePickerDescriptionItemProvider == null) {
			eefImagePickerDescriptionItemProvider = new EEFImagePickerDescriptionItemProvider(this);
		}

		return eefImagePickerDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFTableDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFTableDescriptionItemProvider eefTableDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFTableDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFTableDescriptionAdapter() {
		if (eefTableDescriptionItemProvider == null) {
			eefTableDescriptionItemProvider = new EEFTableDescriptionItemProvider(this);
		}

		return eefTableDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFColumnDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFColumnDescriptionItemProvider eefColumnDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFColumnDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFColumnDescriptionAdapter() {
		if (eefColumnDescriptionItemProvider == null) {
			eefColumnDescriptionItemProvider = new EEFColumnDescriptionItemProvider(this);
		}

		return eefColumnDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFLineDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFLineDescriptionItemProvider eefLineDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFLineDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFLineDescriptionAdapter() {
		if (eefLineDescriptionItemProvider == null) {
			eefLineDescriptionItemProvider = new EEFLineDescriptionItemProvider(this);
		}

		return eefLineDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFAdapterFactoryTableStructureDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFAdapterFactoryTableStructureDescriptionItemProvider eefAdapterFactoryTableStructureDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFAdapterFactoryTableStructureDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFAdapterFactoryTableStructureDescriptionAdapter() {
		if (eefAdapterFactoryTableStructureDescriptionItemProvider == null) {
			eefAdapterFactoryTableStructureDescriptionItemProvider = new EEFAdapterFactoryTableStructureDescriptionItemProvider(this);
		}

		return eefAdapterFactoryTableStructureDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFGroupStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFGroupStyleItemProvider eefGroupStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFGroupStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFGroupStyleAdapter() {
		if (eefGroupStyleItemProvider == null) {
			eefGroupStyleItemProvider = new EEFGroupStyleItemProvider(this);
		}

		return eefGroupStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFGroupConditionalStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFGroupConditionalStyleItemProvider eefGroupConditionalStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFGroupConditionalStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFGroupConditionalStyleAdapter() {
		if (eefGroupConditionalStyleItemProvider == null) {
			eefGroupConditionalStyleItemProvider = new EEFGroupConditionalStyleItemProvider(this);
		}

		return eefGroupConditionalStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFGroupStyleCustomization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFGroupStyleCustomizationItemProvider eefGroupStyleCustomizationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFGroupStyleCustomization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFGroupStyleCustomizationAdapter() {
		if (eefGroupStyleCustomizationItemProvider == null) {
			eefGroupStyleCustomizationItemProvider = new EEFGroupStyleCustomizationItemProvider(this);
		}

		return eefGroupStyleCustomizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFTextStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFTextStyleItemProvider eefTextStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFTextStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFTextStyleAdapter() {
		if (eefTextStyleItemProvider == null) {
			eefTextStyleItemProvider = new EEFTextStyleItemProvider(this);
		}

		return eefTextStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFTextConditionalStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFTextConditionalStyleItemProvider eefTextConditionalStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFTextConditionalStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFTextConditionalStyleAdapter() {
		if (eefTextConditionalStyleItemProvider == null) {
			eefTextConditionalStyleItemProvider = new EEFTextConditionalStyleItemProvider(this);
		}

		return eefTextConditionalStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFTextStyleCustomization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFTextStyleCustomizationItemProvider eefTextStyleCustomizationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFTextStyleCustomization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFTextStyleCustomizationAdapter() {
		if (eefTextStyleCustomizationItemProvider == null) {
			eefTextStyleCustomizationItemProvider = new EEFTextStyleCustomizationItemProvider(this);
		}

		return eefTextStyleCustomizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFCheckboxStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFCheckboxStyleItemProvider eefCheckboxStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFCheckboxStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFCheckboxStyleAdapter() {
		if (eefCheckboxStyleItemProvider == null) {
			eefCheckboxStyleItemProvider = new EEFCheckboxStyleItemProvider(this);
		}

		return eefCheckboxStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFCheckboxConditionalStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFCheckboxConditionalStyleItemProvider eefCheckboxConditionalStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFCheckboxConditionalStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFCheckboxConditionalStyleAdapter() {
		if (eefCheckboxConditionalStyleItemProvider == null) {
			eefCheckboxConditionalStyleItemProvider = new EEFCheckboxConditionalStyleItemProvider(this);
		}

		return eefCheckboxConditionalStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFCheckboxStyleCustomization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFCheckboxStyleCustomizationItemProvider eefCheckboxStyleCustomizationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFCheckboxStyleCustomization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFCheckboxStyleCustomizationAdapter() {
		if (eefCheckboxStyleCustomizationItemProvider == null) {
			eefCheckboxStyleCustomizationItemProvider = new EEFCheckboxStyleCustomizationItemProvider(this);
		}

		return eefCheckboxStyleCustomizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFLabelStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFLabelStyleItemProvider eefLabelStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFLabelStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFLabelStyleAdapter() {
		if (eefLabelStyleItemProvider == null) {
			eefLabelStyleItemProvider = new EEFLabelStyleItemProvider(this);
		}

		return eefLabelStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFLabelConditionalStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFLabelConditionalStyleItemProvider eefLabelConditionalStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFLabelConditionalStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFLabelConditionalStyleAdapter() {
		if (eefLabelConditionalStyleItemProvider == null) {
			eefLabelConditionalStyleItemProvider = new EEFLabelConditionalStyleItemProvider(this);
		}

		return eefLabelConditionalStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFLabelStyleCustomization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFLabelStyleCustomizationItemProvider eefLabelStyleCustomizationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFLabelStyleCustomization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFLabelStyleCustomizationAdapter() {
		if (eefLabelStyleCustomizationItemProvider == null) {
			eefLabelStyleCustomizationItemProvider = new EEFLabelStyleCustomizationItemProvider(this);
		}

		return eefLabelStyleCustomizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFRadioStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFRadioStyleItemProvider eefRadioStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFRadioStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFRadioStyleAdapter() {
		if (eefRadioStyleItemProvider == null) {
			eefRadioStyleItemProvider = new EEFRadioStyleItemProvider(this);
		}

		return eefRadioStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFRadioConditionalStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFRadioConditionalStyleItemProvider eefRadioConditionalStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFRadioConditionalStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFRadioConditionalStyleAdapter() {
		if (eefRadioConditionalStyleItemProvider == null) {
			eefRadioConditionalStyleItemProvider = new EEFRadioConditionalStyleItemProvider(this);
		}

		return eefRadioConditionalStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFRadioStyleCustomization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFRadioStyleCustomizationItemProvider eefRadioStyleCustomizationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFRadioStyleCustomization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFRadioStyleCustomizationAdapter() {
		if (eefRadioStyleCustomizationItemProvider == null) {
			eefRadioStyleCustomizationItemProvider = new EEFRadioStyleCustomizationItemProvider(this);
		}

		return eefRadioStyleCustomizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFLinkStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFLinkStyleItemProvider eefLinkStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFLinkStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFLinkStyleAdapter() {
		if (eefLinkStyleItemProvider == null) {
			eefLinkStyleItemProvider = new EEFLinkStyleItemProvider(this);
		}

		return eefLinkStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFLinkConditionalStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFLinkConditionalStyleItemProvider eefLinkConditionalStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFLinkConditionalStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFLinkConditionalStyleAdapter() {
		if (eefLinkConditionalStyleItemProvider == null) {
			eefLinkConditionalStyleItemProvider = new EEFLinkConditionalStyleItemProvider(this);
		}

		return eefLinkConditionalStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFLinkStyleCustomization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFLinkStyleCustomizationItemProvider eefLinkStyleCustomizationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFLinkStyleCustomization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFLinkStyleCustomizationAdapter() {
		if (eefLinkStyleCustomizationItemProvider == null) {
			eefLinkStyleCustomizationItemProvider = new EEFLinkStyleCustomizationItemProvider(this);
		}

		return eefLinkStyleCustomizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFSelectStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFSelectStyleItemProvider eefSelectStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFSelectStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFSelectStyleAdapter() {
		if (eefSelectStyleItemProvider == null) {
			eefSelectStyleItemProvider = new EEFSelectStyleItemProvider(this);
		}

		return eefSelectStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFSelectConditionalStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFSelectConditionalStyleItemProvider eefSelectConditionalStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFSelectConditionalStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFSelectConditionalStyleAdapter() {
		if (eefSelectConditionalStyleItemProvider == null) {
			eefSelectConditionalStyleItemProvider = new EEFSelectConditionalStyleItemProvider(this);
		}

		return eefSelectConditionalStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFSelectStyleCustomization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFSelectStyleCustomizationItemProvider eefSelectStyleCustomizationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFSelectStyleCustomization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFSelectStyleCustomizationAdapter() {
		if (eefSelectStyleCustomizationItemProvider == null) {
			eefSelectStyleCustomizationItemProvider = new EEFSelectStyleCustomizationItemProvider(this);
		}

		return eefSelectStyleCustomizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFTreeStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFTreeStyleItemProvider eefTreeStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFTreeStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFTreeStyleAdapter() {
		if (eefTreeStyleItemProvider == null) {
			eefTreeStyleItemProvider = new EEFTreeStyleItemProvider(this);
		}

		return eefTreeStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFTreeConditionalStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFTreeConditionalStyleItemProvider eefTreeConditionalStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFTreeConditionalStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFTreeConditionalStyleAdapter() {
		if (eefTreeConditionalStyleItemProvider == null) {
			eefTreeConditionalStyleItemProvider = new EEFTreeConditionalStyleItemProvider(this);
		}

		return eefTreeConditionalStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFTreeStyleCustomization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFTreeStyleCustomizationItemProvider eefTreeStyleCustomizationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFTreeStyleCustomization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFTreeStyleCustomizationAdapter() {
		if (eefTreeStyleCustomizationItemProvider == null) {
			eefTreeStyleCustomizationItemProvider = new EEFTreeStyleCustomizationItemProvider(this);
		}

		return eefTreeStyleCustomizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFTableStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFTableStyleItemProvider eefTableStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFTableStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFTableStyleAdapter() {
		if (eefTableStyleItemProvider == null) {
			eefTableStyleItemProvider = new EEFTableStyleItemProvider(this);
		}

		return eefTableStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFTableConditionalStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFTableConditionalStyleItemProvider eefTableConditionalStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFTableConditionalStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFTableConditionalStyleAdapter() {
		if (eefTableConditionalStyleItemProvider == null) {
			eefTableConditionalStyleItemProvider = new EEFTableConditionalStyleItemProvider(this);
		}

		return eefTableConditionalStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFTableStyleCustomization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFTableStyleCustomizationItemProvider eefTableStyleCustomizationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFTableStyleCustomization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFTableStyleCustomizationAdapter() {
		if (eefTableStyleCustomizationItemProvider == null) {
			eefTableStyleCustomizationItemProvider = new EEFTableStyleCustomizationItemProvider(this);
		}

		return eefTableStyleCustomizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFLineStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFLineStyleItemProvider eefLineStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFLineStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFLineStyleAdapter() {
		if (eefLineStyleItemProvider == null) {
			eefLineStyleItemProvider = new EEFLineStyleItemProvider(this);
		}

		return eefLineStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFLineConditionalStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFLineConditionalStyleItemProvider eefLineConditionalStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFLineConditionalStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFLineConditionalStyleAdapter() {
		if (eefLineConditionalStyleItemProvider == null) {
			eefLineConditionalStyleItemProvider = new EEFLineConditionalStyleItemProvider(this);
		}

		return eefLineConditionalStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFLineStyleCustomization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFLineStyleCustomizationItemProvider eefLineStyleCustomizationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFLineStyleCustomization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFLineStyleCustomizationAdapter() {
		if (eefLineStyleCustomizationItemProvider == null) {
			eefLineStyleCustomizationItemProvider = new EEFLineStyleCustomizationItemProvider(this);
		}

		return eefLineStyleCustomizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFColumnStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFColumnStyleItemProvider eefColumnStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFColumnStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFColumnStyleAdapter() {
		if (eefColumnStyleItemProvider == null) {
			eefColumnStyleItemProvider = new EEFColumnStyleItemProvider(this);
		}

		return eefColumnStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFColumnConditionalStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFColumnConditionalStyleItemProvider eefColumnConditionalStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFColumnConditionalStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFColumnConditionalStyleAdapter() {
		if (eefColumnConditionalStyleItemProvider == null) {
			eefColumnConditionalStyleItemProvider = new EEFColumnConditionalStyleItemProvider(this);
		}

		return eefColumnConditionalStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFColumnStyleCustomization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFColumnStyleCustomizationItemProvider eefColumnStyleCustomizationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFColumnStyleCustomization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFColumnStyleCustomizationAdapter() {
		if (eefColumnStyleCustomizationItemProvider == null) {
			eefColumnStyleCustomizationItemProvider = new EEFColumnStyleCustomizationItemProvider(this);
		}

		return eefColumnStyleCustomizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFQuickFix} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFQuickFixItemProvider eefQuickFixItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFQuickFix}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFQuickFixAdapter() {
		if (eefQuickFixItemProvider == null) {
			eefQuickFixItemProvider = new EEFQuickFixItemProvider(this);
		}

		return eefQuickFixItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.eef.EEFValidation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EEFValidationItemProvider eefValidationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.eef.EEFValidation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEEFValidationAdapter() {
		if (eefValidationItemProvider == null) {
			eefValidationItemProvider = new EEFValidationItemProvider(this);
		}

		return eefValidationItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (eefViewDescriptionItemProvider != null)
			eefViewDescriptionItemProvider.dispose();
		if (eefPageDescriptionItemProvider != null)
			eefPageDescriptionItemProvider.dispose();
		if (eefGroupDescriptionItemProvider != null)
			eefGroupDescriptionItemProvider.dispose();
		if (eefContainerDescriptionItemProvider != null)
			eefContainerDescriptionItemProvider.dispose();
		if (eefJavaExtensionDescriptionItemProvider != null)
			eefJavaExtensionDescriptionItemProvider.dispose();
		if (eefInterpretedTableStructureDescriptionItemProvider != null)
			eefInterpretedTableStructureDescriptionItemProvider.dispose();
		if (eefAdapterFactoryTreeStructureDescriptionItemProvider != null)
			eefAdapterFactoryTreeStructureDescriptionItemProvider.dispose();
		if (eefInterpretedTreeStructureDescriptionItemProvider != null)
			eefInterpretedTreeStructureDescriptionItemProvider.dispose();
		if (eefTextDescriptionItemProvider != null)
			eefTextDescriptionItemProvider.dispose();
		if (eefCheckboxDescriptionItemProvider != null)
			eefCheckboxDescriptionItemProvider.dispose();
		if (eefSelectDescriptionItemProvider != null)
			eefSelectDescriptionItemProvider.dispose();
		if (eefLabelDescriptionItemProvider != null)
			eefLabelDescriptionItemProvider.dispose();
		if (eefRadioDescriptionItemProvider != null)
			eefRadioDescriptionItemProvider.dispose();
		if (eefTreeDialogSelectDescriptionItemProvider != null)
			eefTreeDialogSelectDescriptionItemProvider.dispose();
		if (eefLinkDescriptionItemProvider != null)
			eefLinkDescriptionItemProvider.dispose();
		if (eefImageDescriptionItemProvider != null)
			eefImageDescriptionItemProvider.dispose();
		if (eefTreeDescriptionItemProvider != null)
			eefTreeDescriptionItemProvider.dispose();
		if (eefImagePickerDescriptionItemProvider != null)
			eefImagePickerDescriptionItemProvider.dispose();
		if (eefTableDescriptionItemProvider != null)
			eefTableDescriptionItemProvider.dispose();
		if (eefColumnDescriptionItemProvider != null)
			eefColumnDescriptionItemProvider.dispose();
		if (eefLineDescriptionItemProvider != null)
			eefLineDescriptionItemProvider.dispose();
		if (eefAdapterFactoryTableStructureDescriptionItemProvider != null)
			eefAdapterFactoryTableStructureDescriptionItemProvider.dispose();
		if (eefGroupStyleItemProvider != null)
			eefGroupStyleItemProvider.dispose();
		if (eefGroupConditionalStyleItemProvider != null)
			eefGroupConditionalStyleItemProvider.dispose();
		if (eefGroupStyleCustomizationItemProvider != null)
			eefGroupStyleCustomizationItemProvider.dispose();
		if (eefTextStyleItemProvider != null)
			eefTextStyleItemProvider.dispose();
		if (eefTextConditionalStyleItemProvider != null)
			eefTextConditionalStyleItemProvider.dispose();
		if (eefTextStyleCustomizationItemProvider != null)
			eefTextStyleCustomizationItemProvider.dispose();
		if (eefCheckboxStyleItemProvider != null)
			eefCheckboxStyleItemProvider.dispose();
		if (eefCheckboxConditionalStyleItemProvider != null)
			eefCheckboxConditionalStyleItemProvider.dispose();
		if (eefCheckboxStyleCustomizationItemProvider != null)
			eefCheckboxStyleCustomizationItemProvider.dispose();
		if (eefLabelStyleItemProvider != null)
			eefLabelStyleItemProvider.dispose();
		if (eefLabelConditionalStyleItemProvider != null)
			eefLabelConditionalStyleItemProvider.dispose();
		if (eefLabelStyleCustomizationItemProvider != null)
			eefLabelStyleCustomizationItemProvider.dispose();
		if (eefRadioStyleItemProvider != null)
			eefRadioStyleItemProvider.dispose();
		if (eefRadioConditionalStyleItemProvider != null)
			eefRadioConditionalStyleItemProvider.dispose();
		if (eefRadioStyleCustomizationItemProvider != null)
			eefRadioStyleCustomizationItemProvider.dispose();
		if (eefLinkStyleItemProvider != null)
			eefLinkStyleItemProvider.dispose();
		if (eefLinkConditionalStyleItemProvider != null)
			eefLinkConditionalStyleItemProvider.dispose();
		if (eefLinkStyleCustomizationItemProvider != null)
			eefLinkStyleCustomizationItemProvider.dispose();
		if (eefSelectStyleItemProvider != null)
			eefSelectStyleItemProvider.dispose();
		if (eefSelectConditionalStyleItemProvider != null)
			eefSelectConditionalStyleItemProvider.dispose();
		if (eefSelectStyleCustomizationItemProvider != null)
			eefSelectStyleCustomizationItemProvider.dispose();
		if (eefTreeStyleItemProvider != null)
			eefTreeStyleItemProvider.dispose();
		if (eefTreeConditionalStyleItemProvider != null)
			eefTreeConditionalStyleItemProvider.dispose();
		if (eefTreeStyleCustomizationItemProvider != null)
			eefTreeStyleCustomizationItemProvider.dispose();
		if (eefTableStyleItemProvider != null)
			eefTableStyleItemProvider.dispose();
		if (eefTableConditionalStyleItemProvider != null)
			eefTableConditionalStyleItemProvider.dispose();
		if (eefTableStyleCustomizationItemProvider != null)
			eefTableStyleCustomizationItemProvider.dispose();
		if (eefLineStyleItemProvider != null)
			eefLineStyleItemProvider.dispose();
		if (eefLineConditionalStyleItemProvider != null)
			eefLineConditionalStyleItemProvider.dispose();
		if (eefLineStyleCustomizationItemProvider != null)
			eefLineStyleCustomizationItemProvider.dispose();
		if (eefColumnStyleItemProvider != null)
			eefColumnStyleItemProvider.dispose();
		if (eefColumnConditionalStyleItemProvider != null)
			eefColumnConditionalStyleItemProvider.dispose();
		if (eefColumnStyleCustomizationItemProvider != null)
			eefColumnStyleCustomizationItemProvider.dispose();
		if (eefQuickFixItemProvider != null)
			eefQuickFixItemProvider.dispose();
		if (eefValidationItemProvider != null)
			eefValidationItemProvider.dispose();
	}

}
