/*
 * generated by Xtext
 */
package org.eclipse.sirius.expression.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExpressionDSLUiModule extends org.eclipse.sirius.expression.dsl.ui.AbstractExpressionDSLUiModule {
	public ExpressionDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
