/*
 * generated by Xtext
 */
package org.eclipse.sirius.expression.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ExpressionDSLUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.eclipse.sirius.expression.dsl.ui.internal.ExpressionDSLActivator.getInstance().getInjector("org.eclipse.sirius.expression.dsl.ExpressionDSL");
	}
	
}
