/*
 * generated by Xtext
 */
package org.eclipse.emf.eef.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.emf.eef.ui.internal.ModelingBotActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ModelingBotExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ModelingBotActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ModelingBotActivator.getInstance().getInjector(ModelingBotActivator.ORG_ECLIPSE_EMF_EEF_MODELINGBOT);
	}
	
}
